/**:
  ros__parameters:
    data_root: "/home/radxa/realflight_ws/data/realflight_traj_new_H (m2=0.1,rg=[0,-0.028])"
    timer_period: 0.01
    payload_pose_topic: "/vrpn_mocap/multilift_payload/pose"
    l: 1.0
    kq: 9.5
    kw: 3.4
    z_weight: 0.0
    thrust_bias: 0.0
    alpha_gain: 0.0
    payload_is_enu: true
    log_path: ""
