/**:
  ros__parameters:
    mode: "realflight"
    payload_input: "pose"
    use_payload_stamp_time: false
    data_root: "data/realflight_traj_vertical_V_6_rpx5"
    use_raw_traj: false
    trajectory_csv: ""
    cable_csv: ""
    timer_period: 0.01
    payload_pose_topic: "/vrpn_mocap/multilift_payload/pose"
    payload_mass: 0.220
    payload_added_mass: 0.20
    payload_rp: [0.05, 0.0, 0.0]
    payload_radius: 0.245
    feedforward_weight: 0.0
    feedback_weight: 0.0
    yaw_setpoint: 3.141592653589793
    payload_is_enu: true
    enable_log: false
    enable_debug_log: false
    log_path: "/home/carlson/ros2/realflight_ws/realflight_log"
    debug_log_path: "/home/carlson/ros2/realflight_ws/realflight_log"
    debug_log_period: 0.2
    drone_mass: 0.32
    use_wall_timer: true
