/**:
  ros__parameters:
    mode: "realflight"
    payload_input: "pose"
    use_payload_stamp_time: false
    data_root: "data/realflight_traj_vertical_V_6_x_5cm"
    use_raw_traj: false
    trajectory_csv: ""
    cable_csv: ""
    payload_csv: ""
    kfb_csv: ""
    timer_period: 0.01
    payload_pose_topic: "/vrpn_mocap/multilift_payload/pose"
    m1: 0.160
    m2: 0.20
    rp: [0.05, 0.0, 0.0]
    payload_radius: 0.175
    cable_length: 1.0
    feedforward_weight: 1.0
    feedback_weight: 1.0
    alpha_gain: 1.0
    yaw_setpoint: 3.141592653589793
    payload_is_enu: true
    delta_p_max: 0.03
    j_max: 30.0
    omega: 5.0
    delta_mu_max: 0.2
    delta_mu_j_max: 1000000.0
    delta_mu_omega: 5.0
    delta_mu_acc_enable: 1.0
    enable_log: false
    log_path: "/home/radxa/realflight_ws/realflight_log"
    enable_debug_log: false
    debug_log_path: "/home/radxa/realflight_ws/realflight_log"
    debug_log_period: 0.2
    drone_mass: 0.32
    use_wall_timer: true
